# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://elog.io/
title: Elog.io
email: hello@elog.io
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: twitter
    title: "@elog_io"
    url: https://twitter.com/elog_io
  - icon: send
    title: "hello@elog.io"
    url: "mailto:hello@elog.io"
  - icon: github
    title: github
    url: https://github.com/commonsmachinery

download:
  - title: Chrome
    url: https://chrome.google.com/webstore/detail/elogio-browser-extension/fggflpkcoiangfbhbekafhpkijbglcmi
  - title: Firefox
    url: http://elog.io/dl/firefox-0.9.0.xpi

